liip_imagine:
    driver: "gd" # Utilisez "gd" ou "imagick" selon votre environnement

    resolvers:
        my_resolver:
            web_path:
                web_root: '%kernel.project_dir%/public'
                cache_prefix: '/media/cache/resize_500/'

    filter_sets:
        cache: ~
        resize_500:
            quality: 100
            filters:
                auto_rotate: {}
                thumbnail: { size: [null, 400], mode: outbound }

    cache: my_cache
